junit_tests(
	name='scala',
	sources=rglobs('*.scala'),
	resources=['swara-examples/src/test/resources'],
	dependencies=[
		'swara-examples/src/main/scala',
		'3rdparty/jvm:junit',
		'3rdparty/jvm:scalatest',
	]
)

